# Generated by Django 4.2.11 on 2024-06-19 13:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Re', 'Residential estate'), ('Cm', 'Commmercial estate'), ('Id', 'Industrial estate'), ('La', 'Land estate'), ('Ge', 'governmental estate')], default='La', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(blank=True, default='', max_length=100, null=True), unique=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('is_negotiable', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/property/')),
                ('location', models.CharField(max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
